jobs:
- deployment: DeployAppPackage
  pool:
    vmImage: $(vmImage)

  variables:
  - template: ${{parameters.deployYmlChildPath}}
  environment: ${{variables.environment}}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          displayName: 'Download artifact'
          artifact: $(artifactName)

        - task: NuGetAuthenticate@1
          displayName: 'Auth to nuget.org'   # uses the NuGet service connection you created

        - powershell: |
            $source = "https://api.nuget.org/v3/index.json"
            $apiKey = $Env:NUGET_AUTH_TOKEN
            Get-ChildItem "$(Pipeline.Workspace)\$(artifactName)" -Recurse -Filter *.nupkg |
              Where-Object { $_.Name -notlike "*.symbols.nupkg" } |
              ForEach-Object {
                dotnet nuget push $_.FullName --source $source --api-key $apiKey --skip-duplicate
              }
          displayName: 'dotnet nuget push'